# Pandas Notes

Here I upload whatever I learned about Pandas

## Basics Codes

There are some basic codes on reading and displaying a dataframe:

In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], columns=['A', 'B', 'C'], index=['row1', 'row2', 'row3', 'row4'])

The is a prettier way to generate a Data Frame:

In [2]:
new_df = pd.DataFrame({

    "name": ["Alice", "Bob", "Charlie", "David"],
    "age": [25, 30, 35, 40],
    "city": ["New York", "Los Angeles", "Chicago", "Houston"]
})

new_series = pd.Series([10, 20, 30, 40], name='numbers')

In [3]:
df.head() # shows the first 5 rows of the dataframe by default
df.head(2) # shows the first 2 rows of the dataframe

      A  B  C
row1  1  2  3
row2  4  5  6

In [4]:
df.tail() # shows the last 5 rows of the dataframe by default
df.tail(2) # shows the last 2 rows of the dataframe

       A   B   C
row3   7   8   9
row4  10  11  12

In [5]:
df.info() # shows a concise summary of the dataframe, including the number of non-null values, data types, and memory usage
df.describe() # shows summary statistics of the dataframe, including count, mean, standard deviation, minimum, and maximum values for each column

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, row1 to row4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       4 non-null      int64
 1   B       4 non-null      int64
 2   C       4 non-null      int64
dtypes: int64(3)
memory usage: 128.0+ bytes

               A          B          C
count   4.000000   4.000000   4.000000
mean    5.500000   6.500000   7.500000
std     3.872983   3.872983   3.872983
min     1.000000   2.000000   3.000000
25%     3.250000   4.250000   5.250000
50%     5.500000   6.500000   7.500000
75%     7.750000   8.750000   9.750000
max    10.000000  11.000000  12.000000

In [6]:
df.columns.tolist() # shows the column names of the dataframe
df.index.tolist() # shows the index labels of the dataframe

['row1', 'row2', 'row3', 'row4']

In [7]:
df.size # shows the number of elements
df.shape # shows the shape of data frame

(4, 3)

## Loading DataFrames from Files

There are lighter data frames beside .csv like .feather or .parquest

In [8]:
coffee = pd.read_csv('https://raw.githubusercontent.com/Nader1995/complete-pandas-tutorial/refs/heads/master/warmup-data/coffee.csv')
# coffee = pd.read_feather('...')
# coffee = pd.read_excel('...')
# coffee = pd.read_parquet('...')

If we want to resave our data in a specific format, we can use the following commands:

In [9]:
df.to_csv('my_dataframe.csv', index=False) # saves the dataframe to a CSV file without the index
# df.to_feather('...')
# df.to_excel('...')
# df.to_parquet('...')

## Accessing Data Using Pandas

In [10]:
coffee.sample(5) # shows a random sample of rows from the dataframe, where n is the number of rows to return

          Day Coffee Type  Units Sold
2     Tuesday    Espresso          30
5   Wednesday       Latte          25
10   Saturday    Espresso          45
3     Tuesday       Latte          20
11   Saturday       Latte          35

In [11]:
# coffee.loc[Row Labels, Column Labels]
coffee.loc[0:3, ['Coffee Type', 'Units Sold']]

  Coffee Type  Units Sold
0    Espresso          25
1       Latte          15
2    Espresso          30
3       Latte          20

In [12]:
# coffee.iloc[Row Positions, Column Positions]
coffee.iloc[0:3, 1:3]

  Coffee Type  Units Sold
0    Espresso          25
1       Latte          15
2    Espresso          30

* Hint: There is a difference between .loc and .iloc where in '.iloc' 0:10 indicates 0, ..., 9 and in '.loc' 0:10 is 0, ..., 10.

To find specific values we can use:

In [13]:
coffee.at[1, 'Coffee Type'] # shows the value at the specified row label and column label
# coffee.iat[1, 1] # shows the value at the specified row position and column position

'Latte'

In [14]:
coffee.sort_values('Units Sold', ascending=False) # sorts the dataframe by the specified column in descending order

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
2     Tuesday    Espresso          30
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
3     Tuesday       Latte          20
1      Monday       Latte          15

## Filtering Data

Let's deal with a more interesting data set:

In [15]:
bios = pd.read_csv('https://raw.githubusercontent.com/Nader1995/complete-pandas-tutorial/refs/heads/master/data/bios.csv')

In [16]:
bios.loc[bios['height_cm']>220, ['name', 'born_country', 'height_cm']] # shows the name and height of all individuals taller than 220 cm

                   name born_country  height_cm
5673     Gunther Behnke          GER      221.0
5781     Tommy Burleson          USA      223.0
6978    Arvydas Sabonis          LTU      223.0
89070          Yao Ming          CHN      226.0
89075    Roberto Dueñas          ESP      221.0
120266     Zhang Zhaoxu          CHN      221.0

In [17]:
bios[(bios['height_cm']>215) & (bios['born_country']=='USA')] # shows the name and height of all individuals taller than 215 cm and born in the USA

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
6722,6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
6937,6972,David Robinson,1965-08-06,Key West,Florida,USA,United States,216.0,107.0,NaN
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN

In [18]:
bios[bios['name'].str.contains('keith', case=False)] # shows the name and height of all individuals whose name contains 'keith', ignoring case sensitivity

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,NaN,NaN,1993-01-09
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22
...,...,...,...,...,...,...,...,...,...,...
109900,111105,Keith Cumberpatch,1927-08-25,Christchurch,Canterbury,NZL,New Zealand,NaN,NaN,2013-11-15
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN
117676,119195,Duncan Keith,1983-07-16,Winnipeg,Manitoba,CAN,Canada,185.0,88.0,NaN
122121,124176,Keith Ferguson,1979-09-07,Sale,Victoria,AUS,Australia,176.0,78.0,NaN
127310,129749,Tracy Keith-Matchitt,1990-03-30,Palmerston North,Manawatu-Wanganui,NZL,Cook Islands,167.0,60.0,NaN

In [19]:
bios[bios['born_country'].isin(['USA', 'GBR']) & bios['name'].str.contains('keith', case=False)] # shows the name and height of all individuals born in the USA, Germany, or Canada, ignoring case sensitivity

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22
14577,14674,Keith Harrison,1933-03-28,Birmingham,England,GBR,Great Britain,NaN,NaN,NaN
16166,16281,Keith Reynolds,1963-12-25,Solihull,England,GBR,Great Britain,173.0,68.0,NaN
18734,18862,Keith Sinclair,1945-06-26,Sunderland,England,GBR,Great Britain,190.0,79.0,NaN
29897,30123,Keith Langley,1961-06-03,Aldershot,England,GBR,Great Britain,173.0,70.0,NaN
34011,34275,Keith Remfry,1947-11-17,Ealing,England,GBR,Great Britain,193.0,114.0,2015-09-16
46885,47234,Keith Collin,1937-01-18,Marylebone,England,GBR,Great Britain,168.0,63.0,1991-03-06
50929,51288,Keith Carter,1924-08-30,Akron,Ohio,USA,United States,NaN,NaN,2013-05-03
51185,51544,Keith Russell,1948-01-15,Mesa,Arizona,USA,United States,188.0,73.0,NaN
52913,53288,Keith Erickson,1944-04-19,San Francisco,California,USA,United States,196.0,86.0,NaN
55317,55712,Keith Boxell,1958-05-06,Clapham,England,GBR,Great Britain,170.0,87.0,NaN
57818,58226,Keith Peache,1947-08-10,Lewisham,England,GBR,Great Britain,180.0,98.0,NaN
61748,62202,Keith Grogono,1912-11-04,Stratford,England,GBR,Great Britain,NaN,NaN,1999-03-22
62620,63086,Keith Musto,1936-01-12,Rochford,England,GBR,Great Britain,174.0,72.0,NaN
62678,63144,Keith Notary,1960-01-22,Merritt Island,Florida,USA,United States,170.0,66.0,NaN
68324,68841,Keith Angus,1943-04-05,Sheffield,England,GBR,Great Britain,170.0,59.0,NaN
68472,68989,Keith Cullen,1972-06-13,Ilford,England,GBR,Great Britain,177.0,61.0,NaN
68997,69514,Keith Stock,1957-03-18,Woolwich,England,GBR,Great Britain,176.0,73.0,NaN
77550,78141,Keith Brantly,1962-05-23,Scott Air Force Base,Illinois,USA,United States,180.0,64.0,NaN
84097,84766,Keith Christiansen,1944-07-14,International Falls,Minnesota,USA,United States,165.0,69.0,2018-11-05
94646,95413,Keith Meyer,1938-06-20,Geneva,Illinois,USA,United States,NaN,NaN,2010-07-25
95267,96037,Keith Oliver,1947-10-27,Liverpool,England,GBR,Great Britain,172.0,68.0,NaN
96452,97229,Keith Schellenberg,1929-03-13,Middlesbrough,England,GBR,Great Britain,NaN,NaN,2019-10-28
97499,98286,Keith Tkachuk,1972-03-28,Melrose,Massachusetts,USA,United States,188.0,102.0,NaN
98068,98860,Keith Wegeman,1929-08-28,Denver,Colorado,USA,United States,NaN,NaN,1974-08-22
99921,100722,Keith Carney,1970-02-03,Providence,Rhode Island,USA,United States,188.0,93.0,NaN
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN

The code above has too many bios in it. The line below is easier:

In [20]:
bios.query('born_country == "USA" and height_cm > 215') # shows the name and height of all individuals taller than 215 cm and born in the USA using the query method

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
6722,6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
6937,6972,David Robinson,1965-08-06,Key West,Florida,USA,United States,216.0,107.0,NaN
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN

In [21]:
bios.loc[bios['weight_kg'].isnull()] # shows the name and height of all individuals whose weight is missing (NaN)
bios.loc[bios['weight_kg'].notnull()] # shows the name and height of all individuals whose weight is not missing (NaN)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
5,6,Nicolas Chatelain,1970-01-13,Amiens,Somme,FRA,France,181.0,70.0,NaN
6,7,Patrick Chila,1969-11-27,Ris-Orangis,Essonne,FRA,France,180.0,73.0,NaN
...,...,...,...,...,...,...,...,...,...,...
145473,149200,Toms Andersons,1993-11-25,Rīga,Rīga,LAT,Latvia,185.0,86.0,NaN
145474,149201,Nadine Hofstetter,1994-10-21,Romoos,Luzern,SUI,Switzerland,164.0,68.0,NaN
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN

## Adding / Removing Columns

In [22]:
coffee['Price'] = 4.99 # adds a new column 'Price' to the coffee dataframe with a constant value of 4.99 for all rows

In [23]:
coffee.drop('Price', axis=1, inplace=True) # removes the 'Price' column from the coffee dataframe and modifies the original dataframe

* There is an important point on how Pandas stores Data. When you copy a dataset in a new place, then these is a pointer pointing to the previous position of dataset. When when you change the copy_set, it automatically changes the original set as well. The best way to prohibite this modification is to use ".copy" module:
 - coffee_new = coffee # A pointer in coffee_new points to coffee
 - coffee_new = coffee.copy() # A seperate place in memory is used to store the dataset

Also, in order to re-name any element in you dataset:

In [24]:
coffee.rename(columns={'Coffee Type': 'Type'}, inplace=True) # renames the 'OldName' column to 'NewName' in the coffee dataframe and modifies the original dataframe

## Summary Functions and Maps 

Just like maps in math, there are some maps from current dataset to an ideal dataset. 
There are also some methods like .unique, we will disgust:

In [25]:
coffee['USDprice'] = np.random.randint(1, 11, size=len(coffee)) # adds a new column 'price' to the coffee dataframe with random values from the random_prices list

* Different between Module, Function and Method:
  * Module: a python file that contains functions -> in np.random.rand the first .random an np are modules
  * Function: inside a module we have functions that do some job -> np.sqrt()
  * Method: is a function that belongs to an object -> coffee.head() the .head is a method

In [26]:
coffee.Type.unique() # shows the unique values in the 'Type' column of the coffee dataframe
coffee.Type.value_counts() # shows the count of each unique value in the 'Type' column of the coffee dataframe
coffee.Type.describe() # shows summary statistics of the 'Type' column of the coffee dataframe, including count, unique values, top value, and frequency of the top value

count           14
unique           2
top       Espresso
freq             7
Name: Type, dtype: object

In [27]:
USDprice_mean = coffee.USDprice.mean() # calculates the mean of the 'USDprice' column in the coffee dataframe
coffee.USDprice.map(lambda x: x-USDprice_mean) # subtracts the mean from each value in the 'USDprice' column of the coffee dataframe using the map method and a lambda function

0     0.142857
1    -3.857143
2     1.142857
3     1.142857
4     1.142857
5    -3.857143
6    -1.857143
7     1.142857
8     1.142857
9     5.142857
10    3.142857
11   -2.857143
12   -1.857143
13    0.142857
Name: USDprice, dtype: float64

- It is also possible to use .apply() method

In [28]:
def remean_points(row):
    
    row.USDprice = row.USDprice - USDprice_mean
    return row

coffee.apply(remean_points, axis='columns')

          Day      Type  Units Sold  USDprice
0      Monday  Espresso          25  0.142857
1      Monday     Latte          15 -3.857143
2     Tuesday  Espresso          30  1.142857
3     Tuesday     Latte          20  1.142857
4   Wednesday  Espresso          35  1.142857
5   Wednesday     Latte          25 -3.857143
6    Thursday  Espresso          40 -1.857143
7    Thursday     Latte          30  1.142857
8      Friday  Espresso          45  1.142857
9      Friday     Latte          35  5.142857
10   Saturday  Espresso          45  3.142857
11   Saturday     Latte          35 -2.857143
12     Sunday  Espresso          45 -1.857143
13     Sunday     Latte          35  0.142857

* .map() and .apply() do NOT modify the original dataset

In [29]:
coffee.head(1) # shows the first row of the coffee dataframe to verify that the 'USDprice' column has been re-meaned

      Day      Type  Units Sold  USDprice
0  Monday  Espresso          25         5

* There are faster ways:

In [30]:
USDprice_mean = coffee.USDprice.mean() # calculates the mean of the 'USDprice' column in the coffee dataframe
coffee.USDprice - USDprice_mean # subtracts the mean from each value in the 'USDprice' column of the coffee dataframe using vectorized operations

0     0.142857
1    -3.857143
2     1.142857
3     1.142857
4     1.142857
5    -3.857143
6    -1.857143
7     1.142857
8     1.142857
9     5.142857
10    3.142857
11   -2.857143
12   -1.857143
13    0.142857
Name: USDprice, dtype: float64

In [31]:
coffee.Day + '-' + coffee.Type # concatenates the 'Day' and 'Type' columns of the coffee dataframe with a hyphen in between using vectorized string operations

0        Monday-Espresso
1           Monday-Latte
2       Tuesday-Espresso
3          Tuesday-Latte
4     Wednesday-Espresso
5        Wednesday-Latte
6      Thursday-Espresso
7         Thursday-Latte
8        Friday-Espresso
9           Friday-Latte
10     Saturday-Espresso
11        Saturday-Latte
12       Sunday-Espresso
13          Sunday-Latte
dtype: object

## Grouping and Sorting

To put our dataset in groups based on a specific quality, and then perform an action:

General rule:
        
        df.groupby(
        
        'column_to_group'
        )['column_to_analyze'].function()

or 

        df.groupby(
        
        'column_to_group'
        ).column_to_analyze.function()

For example:

In [ ]:
display(

    coffee
)
display(

    coffee.groupby('Type').USDprice.mean()
) # shows the mean of the 'USDprice' column for each unique value in the 'Type' column of the coffee dataframe using the groupby method

display(

    coffee.groupby('Type').USDprice.agg(['mean', 'min', 'max', 'count'])
) # shows the mean, minimum, maximum, and count of the 'USDprice' column for each unique value in the 'Type' column of the coffee dataframe using the groupby method

          Day      Type  Units Sold  USDprice
0      Monday  Espresso          25         5
1      Monday     Latte          15         1
2     Tuesday  Espresso          30         6
3     Tuesday     Latte          20         6
4   Wednesday  Espresso          35         6
5   Wednesday     Latte          25         1
6    Thursday  Espresso          40         3
7    Thursday     Latte          30         6
8      Friday  Espresso          45         6
9      Friday     Latte          35        10
10   Saturday  Espresso          45         8
11   Saturday     Latte          35         2
12     Sunday  Espresso          45         3
13     Sunday     Latte          35         5

Type
Espresso    5.285714
Latte       4.428571
Name: USDprice, dtype: float64

              mean  min  max  count
Type
Espresso  5.285714    3    8      7
Latte     4.428571    1   10      7

* **Multi Index** appears when we categorize a dataset based on more than one factor:

In [ ]:
display(

    coffee.groupby(['Day', 'Type']).USDprice.mean()
) # shows the mean of the 'USDprice' column for each unique combination of values in the 'Day' and 'Type' columns of the coffee dataframe using the groupby method

display(

    coffee.groupby(['Type', 'Day']).USDprice.mean()
) # shows the mean of the 'USDprice' column for each unique combination of values in the 'Type' and 'Day' columns of the coffee dataframe using the groupby method

Day        Type
Friday     Espresso     6.0
           Latte       10.0
Monday     Espresso     5.0
           Latte        1.0
Saturday   Espresso     8.0
           Latte        2.0
Sunday     Espresso     3.0
           Latte        5.0
Thursday   Espresso     3.0
           Latte        6.0
Tuesday    Espresso     6.0
           Latte        6.0
Wednesday  Espresso     6.0
           Latte        1.0
Name: USDprice, dtype: float64

Type      Day
Espresso  Friday        6.0
          Monday        5.0
          Saturday      8.0
          Sunday        3.0
          Thursday      3.0
          Tuesday       6.0
          Wednesday     6.0
Latte     Friday       10.0
          Monday        1.0
          Saturday      2.0
          Sunday        5.0
          Thursday      6.0
          Tuesday       6.0
          Wednesday     1.0
Name: USDprice, dtype: float64

* If we do NOT like **Multi Indexing**, we can always .reset_index:

In [52]:
display(

    coffee.groupby(['Type', 'Day']).USDprice.mean().reset_index()
) # shows the mean of the 'USDprice' column for each unique combination of values in the 'Type' and 'Day' columns of the coffee dataframe using the groupby method and resets the index to a default integer index

        Type        Day  USDprice
0   Espresso     Friday       6.0
1   Espresso     Monday       5.0
2   Espresso   Saturday       8.0
3   Espresso     Sunday       3.0
4   Espresso   Thursday       3.0
5   Espresso    Tuesday       6.0
6   Espresso  Wednesday       6.0
7      Latte     Friday      10.0
8      Latte     Monday       1.0
9      Latte   Saturday       2.0
10     Latte     Sunday       5.0
11     Latte   Thursday       6.0
12     Latte    Tuesday       6.0
13     Latte  Wednesday       1.0

* There is a problem with saving data using .to_csv() or others. It saves the index as well, so next time when we read the file, pandas adds a new index column next to the original index column the file already has, so we have to save dataset without saving the index column, using index=false parameter:

In [35]:
coffee.to_csv('no_index_coffee.csv', index= False) # saves the coffee dataframe to a CSV file without the index

In sorting, we want to re-arrange rows based on some values in a column. 
It is usually in ascending order but you can modify by writing:

    ascending = False

Here is an example:

In [53]:
display(

    coffee.sort_values(by='Units Sold')
) # sorts the coffee dataframe by the 'Units Sold' column in ascending order

display(

    coffee.sort_values(by='Units Sold', ascending= False)
) # sorts the coffee dataframe by the 'Units Sold' column in descending order

          Day      Type  Units Sold  USDprice
1      Monday     Latte          15         1
3     Tuesday     Latte          20         6
0      Monday  Espresso          25         5
5   Wednesday     Latte          25         1
2     Tuesday  Espresso          30         6
7    Thursday     Latte          30         6
4   Wednesday  Espresso          35         6
9      Friday     Latte          35        10
11   Saturday     Latte          35         2
13     Sunday     Latte          35         5
6    Thursday  Espresso          40         3
8      Friday  Espresso          45         6
10   Saturday  Espresso          45         8
12     Sunday  Espresso          45         3

          Day      Type  Units Sold  USDprice
8      Friday  Espresso          45         6
10   Saturday  Espresso          45         8
12     Sunday  Espresso          45         3
6    Thursday  Espresso          40         3
4   Wednesday  Espresso          35         6
9      Friday     Latte          35        10
11   Saturday     Latte          35         2
13     Sunday     Latte          35         5
2     Tuesday  Espresso          30         6
7    Thursday     Latte          30         6
0      Monday  Espresso          25         5
5   Wednesday     Latte          25         1
3     Tuesday     Latte          20         6
1      Monday     Latte          15         1

* Or we can choose more than one parameter to sort:

In [54]:
display(

    coffee.sort_values(by=['Type', 'Units Sold'])
) # sorts the coffee dataframe by the 'Type' column in ascending order and then by the 'Units Sold' column in ascending order within each group of 'Type'

          Day      Type  Units Sold  USDprice
0      Monday  Espresso          25         5
2     Tuesday  Espresso          30         6
4   Wednesday  Espresso          35         6
6    Thursday  Espresso          40         3
8      Friday  Espresso          45         6
10   Saturday  Espresso          45         8
12     Sunday  Espresso          45         3
1      Monday     Latte          15         1
3     Tuesday     Latte          20         6
5   Wednesday     Latte          25         1
7    Thursday     Latte          30         6
9      Friday     Latte          35        10
11   Saturday     Latte          35         2
13     Sunday     Latte          35         5

## Data Types and Missing Values

* We can use .dtype method to know the type of data of a specific column or the whole dataset:

In [51]:
display(coffee.USDprice.dtype) # shows the data type of the 'USDprice' column in the coffee dataframe
display('********************')
display(coffee.dtypes) # shows the data types of all columns in the coffee dataframe

dtype('int64')

'********************'

Day           object
Type          object
Units Sold     int64
USDprice       int64
dtype: object

In order to change data type:

In [49]:
display(coffee.USDprice.astype('float64')) # converts the 'USDprice' column of the coffee dataframe to the float64 data type using the astype method

0      5.0
1      1.0
2      6.0
3      6.0
4      6.0
5      1.0
6      3.0
7      6.0
8      6.0
9     10.0
10     8.0
11     2.0
12     3.0
13     5.0
Name: USDprice, dtype: float64

Missing values: 

We can use 

    .isnull()

to find the rows in a column, containing NaN value.

Also

    .notnull()

does the opposite. It finds the rows not containing NaN values.

The command 

    .isnull().sum()

counts the number of NaN values in a dataset.

The command 

    .fillna(0)
    .fillna('Unknown')
    .fillna(df['specific_column'].mean())

fills the empty data with either 0, or 'Unknown' or the mean value of that column.

If we want to fill a NaN data based on the previous data in that column, we use 

    .ffill() # Forward fill
and to do the opposite, we use

    .bfill() # Backward fill

* Whenever we have a few NaN elements and we are deciding to drop them we can use:

In [45]:
coffee.dropna() # drops all rows with any missing values (NaN) in the coffee dataframe and returns a new dataframe without modifying the original dataframe

          Day      Type  Units Sold  USDprice
0      Monday  Espresso          25         5
1      Monday     Latte          15         1
2     Tuesday  Espresso          30         6
3     Tuesday     Latte          20         6
4   Wednesday  Espresso          35         6
5   Wednesday     Latte          25         1
6    Thursday  Espresso          40         3
7    Thursday     Latte          30         6
8      Friday  Espresso          45         6
9      Friday     Latte          35        10
10   Saturday  Espresso          45         8
11   Saturday     Latte          35         2
12     Sunday  Espresso          45         3
13     Sunday     Latte          35         5

* which drops the **whole row** containing NaN. Yet if we want to just drop the whole row which contains NaN in a specific column we do:

In [46]:
coffee.dropna(subset= ['Day']) # drops all rows with missing values (NaN) in the 'Day' column of the coffee dataframe and returns a new dataframe without modifying the original dataframe

          Day      Type  Units Sold  USDprice
0      Monday  Espresso          25         5
1      Monday     Latte          15         1
2     Tuesday  Espresso          30         6
3     Tuesday     Latte          20         6
4   Wednesday  Espresso          35         6
5   Wednesday     Latte          25         1
6    Thursday  Espresso          40         3
7    Thursday     Latte          30         6
8      Friday  Espresso          45         6
9      Friday     Latte          35        10
10   Saturday  Espresso          45         8
11   Saturday     Latte          35         2
12     Sunday  Espresso          45         3
13     Sunday     Latte          35         5

* By default .dropna() removes the whole row, but if we decide to drop the column:

In [42]:
coffee.dropna(axis=1) # drops any columns that contain missing values (NaN) from the coffee dataframe

          Day      Type  Units Sold  USDprice
0      Monday  Espresso          25         5
1      Monday     Latte          15         1
2     Tuesday  Espresso          30         6
3     Tuesday     Latte          20         6
4   Wednesday  Espresso          35         6
5   Wednesday     Latte          25         1
6    Thursday  Espresso          40         3
7    Thursday     Latte          30         6
8      Friday  Espresso          45         6
9      Friday     Latte          35        10
10   Saturday  Espresso          45         8
11   Saturday     Latte          35         2
12     Sunday  Espresso          45         3
13     Sunday     Latte          35         5

## Renaming and Combining

To conveniently change the name of single or multiple column(s) or row(s) run:

In [48]:
coffee.rename(
    
    columns= {
        'Type': 'Model',
        'USDprice': 'Price'
}) # renames the 'Type' column to 'Model' and the 'USDprice' column to 'Price' in the coffee dataframe

coffee.rename(
    
    index= {
        0:'first',
        1: 'second',
        2: 'third',
        3: 'fourth'          
}) # renames the index labels of the coffee dataframe to 'first', 'second', 'third', and 'fourth' for the first four rows

              Day      Type  Units Sold  USDprice
first      Monday  Espresso          25         5
second     Monday     Latte          15         1
third     Tuesday  Espresso          30         6
fourth    Tuesday     Latte          20         6
4       Wednesday  Espresso          35         6
5       Wednesday     Latte          25         1
6        Thursday  Espresso          40         3
7        Thursday     Latte          30         6
8          Friday  Espresso          45         6
9          Friday     Latte          35        10
10       Saturday  Espresso          45         8
11       Saturday     Latte          35         2
12         Sunday  Espresso          45         3
13         Sunday     Latte          35         5

* As you can see, it does NOT keep the changes.

In order to set a column as index use:

In [44]:
display(coffee)
coffee.set_index('Day') # sets the 'Day' column as the index of the coffee dataframe and modifies the original dataframe

          Day      Type  Units Sold  USDprice
0      Monday  Espresso          25         5
1      Monday     Latte          15         1
2     Tuesday  Espresso          30         6
3     Tuesday     Latte          20         6
4   Wednesday  Espresso          35         6
5   Wednesday     Latte          25         1
6    Thursday  Espresso          40         3
7    Thursday     Latte          30         6
8      Friday  Espresso          45         6
9      Friday     Latte          35        10
10   Saturday  Espresso          45         8
11   Saturday     Latte          35         2
12     Sunday  Espresso          45         3
13     Sunday     Latte          35         5

               Type  Units Sold  USDprice
Day
Monday     Espresso          25         5
Monday        Latte          15         1
Tuesday    Espresso          30         6
Tuesday       Latte          20         6
Wednesday  Espresso          35         6
Wednesday     Latte          25         1
Thursday   Espresso          40         3
Thursday      Latte          30         6
Friday     Espresso          45         6
Friday        Latte          35        10
Saturday   Espresso          45         8
Saturday      Latte          35         2
Sunday     Espresso          45         3
Sunday        Latte          35         5

There many ways to combine two datasets together. We can use either .merge or .concat:

General Rule:

    - pd.merge(
  
    first_set,
    second_set,
    on= 'specific column'
    )

    - pd.concat([first_set, second_set], ignore_index= True)